[workspace]
members = [
    "dic",
    "dict",

    "jojo-core",
    "jojo",

    "error-report",

    "lexing",

    "mexp-parser",
    "mexp-cli",

    "eopl",

    "kanren",

    "lian",

    "cicada",

    "continuum",
]