[workspace]
members = [
    "dic",

    "jojo",
    "jo",

    "error-report",

    "lexing",

    "mexp",
    "mexp-cli",

    "eopl",

    "kanren",

    "wissen",
    "wis",

    "parsing",

    "cicada",
    "cicada-notebook",
    "cicada-db",
    "cic",
]