[workspace]
members = [
    "dic",
    "dict",

    "jojo",
    "jo",

    "error-report",

    "lexing",

    "mexp",
    "mexp-cli",

    "eopl",

    "kanren",

    "wissen",
    "wis",

    "cicada",
    "cic",

    "continuum",
]