[workspace]
members = [
    "dic",
    "dict",

    "jojo",
    "jojo-cli",

    "error-report",

    "lexing",

    "mexp",
    "mexp-cli",

    "eopl",

    "kanren",

    "lian",
    "lian-cli",

    "cicada",
    "cicada-cli",

    "continuum",
]