[package]
name = "error-report"
version = "0.1.0"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"

[build-dependencies]
tangle  = { git = "https://github.com/xieyuheng/tangle-rs" }
