[package]
name = "jojo"
version = "0.1.15"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
jojo-core = { path = "../jojo-core" }
clap     = "2"
linefeed = "0.5"
