[package]
name = "cicada"
version = "0.1.0"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
md-tangle-engine  = { git = "https://github.com/parsing-tech/md-rs" }
org-tangle-engine = { git = "https://github.com/parsing-tech/org-rs" }
